### ISSUE TITLE
Event or connection issue?

### ISSUE THREAD

**Issue by juliensantos87** [sxpert/myhomejs#1]
Hi I'm trying to use your lib but when I use the sample code for monitoring i'm just having this and nothing happend next

2015-09-21T08:45:56.525Z - MON <= _#_1##
2015-09-21T08:45:56.526Z - MON => _99_1##
2015-09-21T08:45:56.529Z - MON <= _#_1##

I was thinking of the events because I tried to listen to more events like "connecting", "connected", ... I never pass in this code.

Any idea?

**Comment by sxpert** [comment]
that is strange, here's what I get with the sample program :

2015-09-24T09:36:05.794Z - MON <= _#_1##
2015-09-24T09:36:05.795Z - MON => _99_1##
2015-09-24T09:36:05.797Z - MON <= _#12133696##
2015-09-24T09:36:05.797Z - MON => *#4294954950##
2015-09-24T09:36:05.798Z - MON <= *#_1##
successfully connected, started monitoring

is your pc in the "authorized ips list" on the bt gateway ? (note, it should not be)

**Comment by juliensantos87** [comment]
I don't know it's strange:

actually to get it work I had to add a changing state where I was stuck here:
https://github.com/sxpert/myhomejs/blob/master/myhome.js#L97

```
self.emit ('connected');
state = STATE_CONNECTED;
```

what do you think? maybe it's because my installation is not secured?

**Comment by sxpert** [comment]
it looks like the gateway is accepting your connexion directly, hence you're jumping straight to STATE_CONNECTED, which I have never tested because my own configuration is different
basically in line 97 it should do the same thing as the current lines 116/117

**Comment by juliensantos87** [comment]
Maybe we could add the connect event when we receive '#1##' ?
What do you think?

**Comment by sxpert** [comment]
try this latest pushed version

**Comment by juliensantos87** [comment]
Hey sorry for the delay...
It works with the last version but it looks like your npm package is not uptodate with it?

**Comment by sxpert** [comment]
nah, didn't take the time to upgrade the npm package

**Comment by juliensantos87** [comment]
@sxpert Hello, could you update your npm package with the latest commit please. this will help me to deploy mine.
Thanks
